#!/bin/sh
limit=20
if [ $# -eq 1 ]; then limit=$1; fi

echo "select from_unixtime(dateTime/1000) as date,data,description as text from sensor order by dateTime desc limit $limit;" | mysql -N --user=davis --password=davis davis
