#!/bin/sh
start=`date +%y-%m-%d`
if [ $# -ge 1 ]; then start=$1; fi
end="2037-12-31"
if [ $# -eq 2 ]; then end=$2; fi

echo "select from_unixtime(dateTime/1000) as date,data,description from sensor where (sensor='A' or sensor='B') and dateTime>=UNIX_TIMESTAMP('$start')*1000 and dateTime<UNIX_TIMESTAMP('$end')*1000 order by dateTime asc" | mysql -N --user=davis --password=davis davis | awk 'BEGIN {date = ""; hour = -1; total = 0; fail = 0} {split($2, t, ":"); if (hour != t[1] && hour >= 0) { printf "%s %s:\t%4s %4s\n",date,hour,total,fail; hour = t[1]; total =  $8; fail = $9;date = $1} else {hour = t[1]; total += $8; fail += $9; date = $1} } END { printf "%s %s:\t%4s %4s\n",date,hour,total,fail}'
