#!/bin/sh
limit=20
if [ $# -eq 1 ]; then limit=$1; fi

echo "select from_unixtime(dateTime/1000) as date,description as text from sensor where sensor in ('T','N','G','H','A', 'B','S') order by dateTime desc limit $limit;" | mysql -N --user=davis --password=davis davis
